# Generated by Django 5.2.1 on 2025-05-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0003_alter_data_user_alter_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
