# Generated by Django 5.2.1 on 2025-05-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0004_alter_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profilee.data'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profilee.data'),
        ),
        migrations.AlterField(
            model_name='education',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profilee.data'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
